
markdown: kramdown

highlighter: rouge
url: https://morvanzhou.github.io
exclude: ['README.md']


# collection and their defaults

collections:
  front-pages:
    output: true
  modules-intro:
    output: true
  loop-description:
    output: false
  tutorials:
    output: true
    permalink: /:collection/:path/
  table-contents:
    output: true
    permalink: /tutorials/:path/


defaults:
  - scope:
      path: "_front-pages"
    values:
      layout: front-page
      enable_ads: true

  - scope:
      path: "_modules-intro"
    values:
      layout: front-page

  - scope:
      path: "_table-contents"
    values:
      layout: table-of-contents

  - scope:
      path: "_tutorials"
    values:
      layout: tutorial-post
      editor: 李良晓
      author: 李良晓
      author-link: "#"
      enable_ads: true
      published: true  #TOD: change back to true

  # module descriptions 
  - scope:
      path: "_loop-description/progress"
    values:
      module: progress

  - scope:
      path: "_loop-description/software"
    values:
      module: software 
  - scope:
      path: "_loop-description/home"
    values:
      module: home
  - scope:
      path: "_loop-description/machine-learning"
    values:
      module: machine-learning
  - scope:
      path: "_loop-description/others"
    values:
      module: others



  # tutorial default
  - scope:
      path: "_tutorials/progress/thoughts"
    values:
      series: 进步思想
      tut-permalink: /tutorials/progress/thoughts
      category: thoughts
      keywords: 自律, 思想, 进步, 减肥
      thumbnail: /static/img/course_cover/np_pd.jpg

  - scope:
      path: "_tutorials/software/linux"
    values:
      series: linux
      tut-permalink: /tutorials/software/linux
      category: linux
      keywords: linux
      thumbnail: /static/img/course_cover/np_pd.jpg

  - scope:
      path: "_tutorials/machine-learning/neuralnetwork"
    values:
      series: 神经网络
      tut-permalink: /tutorials/machine-learning/neuralnetwork/
      category: neuralnetwork
      keywords: 机器学习, 神经网络, 深度学习
      thumbnail: /static/img/course_cover/ML_intro.png

